#!/bin/bash
set -e
cd "$(dirname "$0")"
cd ..
rm -f tests/video.test

if [ ! -f "tests/video.test.original" ]; then
  wget http://jell.yfish.us/media/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv -O tests/video.test.original
fi

cp tests/video.test.original tests/video.test

err() {
  tput setaf 1
  echo
  echo "$1"
  tput sgr0

  rm tests/video.test

  exit 1
}


if ! timeout 1 ./vbrand rm tests/video.test; then
  err "Took too long to realize the file was never even branded"
elif ! timeout 1 ./vbrand tests/video.test; then
  err "Took too long to actually brand"
elif ! timeout 1 ./vbrand tests/video.test; then
  err "Took too long to run vbrand on an already branded file"
fi

rm -f tests/video.test
cp tests/video.test.original tests/video.test
if [[ "`./vbrand tests/video.test`" != "Added brand to tests/video.test" ]] ; then
  err "vbrand did not brand an unbranded file"
elif [[ "`./vbrand tests/video.test`" != "Already branded tests/video.test" ]] ; then
  err "vbrand rebranded a branded file"
fi
./vbrand rm tests/video.test
if ! diff tests/video.test tests/video.test.original; then
  err "Branding and unbranding does not return the original file"
fi


tput setaf 2
echo
echo Passed all tests!
tput sgr0

rm -f tests/video.test
